### ISSUE TITLE
Error When Publishing as Non-Jar Artifact in MavenPublication

### ISSUE THREAD

**Issue by romeara** [StarChart-Labs/flare-publishing-plugins#14]
When the POM scope correction plug-in is applied, and a publication is a non-jar entry, the `publishMavenToLocal` (and other publish tasks) fail with 

```
Caused by: java.lang.NullPointerException: Cannot get property 'dependency' on null object
        at org.starchartlabs.flare.publishing.plugin.PomScopeCorrectionPlugin$_updateScope_closure2$_closure4.doCall(PomScopeCorrectionPlugin.groovy:40)
        at org.starchartlabs.flare.publishing.plugin.PomScopeCorrectionPlugin$_updateScope_closure2.doCall(PomScopeCorrectionPlugin.groovy:39)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.UserCodeAction.execute(UserCodeAction.java:38)
        ... 97 more
```

Example publication configuration:

```
publishing {
    publications {
        zip(MavenPublication) {
       	    artifactId = 'artifact-name'
            artifact someZipTypeTask
        }
    }
}
```

**Comment by romeara** [comment]
Was able to fix locally by replacing plug-in with cooresponding snippet (and null check):

```
project.publishing{
        publications.withType(MavenPublication.class).all{ pub -> 
	        pub.pom.withXml {
	            project.configurations.compile.resolvedConfiguration.firstLevelModuleDependencies.each { dep ->
	            	if(asNode().dependencies[0] != null) {
		                asNode().dependencies[0].dependency.find {
		                    it.artifactId[0].text() == dep.moduleName && it.groupId[0].text() == dep.moduleGroup
		                }?.scope[0]?.value = 'compile'
	                }
	            }
	
	            project.logger.info("Applying compile configuration correction to maven publication '${pub.name}'")
	        }
       	}
    }
```
